services:
  backend:
    build:
      context: ./backend
      target: builder
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/app/src
    command: npx ts-node-dev --respawn --transpile-only --poll src/index.ts
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      target: builder
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    command: npx next dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
